---
title: "MS-S5 The Normal Distribution"
output:
  html_document
---

# [Syllabus](https://syllabus.nesa.nsw.edu.au/assets/mathematics_standard/mathematics-standard-stage-6-syllabus-2017.pdf) {.tabset .tabset-fade .tabset-pills}

## Show

::: {.syllabus}

Students:

* recognise a random variable that is normally distributed, justifying their reasoning, and draw an appropriate 'bell-shaped' frequency distribution curve to represent it
  + identify that the mean and median are approximately equal for data arising from a random variable that is normally distributed
* calculate the $z$-score (standardised score) corresponding to a particular value in a dataset
  + use the formula $z=\frac{x-\bar{x}}{s}$, where $\bar{x}$ is the mean and $s$ is the standard deviation 
  + describe the $z$-score as the number of standard deviations a value lies above or below the mean
  + recognise that the set of $z$-scores for data arising from a random variable that is normally distributed has a mean of 0 and standard deviation of 1
* use calculated $z$-scores to compare scores from different datasets, for example comparingnstudents’ subject examination scores
* use collected data to illustrate that, for normally distributed random variables, approximately 68% of data will have $z$-scores between -1 and 1, approximately 95% of data will have$ $z$-scores between -2 and 2 and approximately 99.7% of data will have $z$-scores between -3 and 3 (known as the empirical rule)
  + apply the empirical rule to a variety of problems
  + indicate by shading where results sit within the normal distribution, eg where the top 10% of data lies
* use $z$-scores to identify probabilities of events less or more extreme than a given event
* use $z$-scores to make judgements related to outcomes of a given event or sets of data

:::


## Hide

#  {.tabset .tabset-fade .tabset-pills}

## Normal distributions

## Properties

## $z$-scores

## Converting scrores

## Comparing datasets

## Applications

